In [1]:
import numpy as np

In [2]:
a = np.arange(6).reshape((3, 2))

In [3]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [4]:
np.reshape(a, (2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
a = np.array([[1,2,3], [4,5,6]])

In [6]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.reshape(a, 6)

array([1, 2, 3, 4, 5, 6])